# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-23 07:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
