# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-07 21:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_auto_20171008_0521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='create_at',
        ),
    ]
