# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-07 22:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_remove_recipe_create_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
